version: '3.8'

services:
  spring:
    build: .
    environment:
      DB_PORT: ${DB_PORT}
      DB_CURRENT: ${DB_CURRENT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: admin
      APPLICATION_NAME: ${APPLICATION_NAME}
    depends_on:
      - postgres
    ports:
      - "8080:${SPRING_PORT}"

  postgres:
    image: postgres:16.1-bullseye
    restart: unless-stopped
    container_name: ${APPLICATION_NAME}-db
    environment:
      POSTGRES_DB: ${DB_CURRENT}
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: ${DB_USERNAME}
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - '5432:${DB_PORT}'

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: ${APPLICATION_NAME}-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres