services:
  spring:
    build: .
    environment:
      DB_PORT: ${DB_PORT}
      DB_CURRENT: ${DB_CURRENT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APPLICATION_NAME: ${APPLICATION_NAME}
    depends_on:
      - postgres
      - fakeaws
    ports:
      - "8080:${SPRING_PORT}"

  postgres:
    image: postgres:16.1-bullseye
    restart: unless-stopped
    container_name: ${APPLICATION_NAME}-db
    environment:
      POSTGRES_DB: ${DB_CURRENT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:${DB_PORT}'

  fakeaws:
    image: minio/minio
    ports:
      - '9000:${FAKE_AWS_PORT}'
      - '9001:${FAKE_AWS_CONSOLE_PORT}'
    environment:
      MINIO_ROOT_USER: ${FAKE_AWS_USER}
      MINIO_ROOT_PASSWORD: ${FAKE_AWS_PSWD}
    volumes:
      - ./data/minio:/data
    restart: unless-stopped
    container_name: fakeaws
    command: server /data --console-address ":9001"